# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f85ca9d5-d6b8-4c4b-a6f8-6b715f49d48f";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DA2C-A523";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6a09a080-da5c-469e-a796-8acdf6c61bac";
      fsType = "ext4";
    };

  fileSystems."/home/fedex/Data" = {
    device = "/dev/vg-data/data";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  fileSystems."/home/fedex/Media" = {
    device = "/dev/vg-data/media";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  fileSystems."/home/fedex/Books" = {
    device = "/dev/vg-data/books";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  fileSystems."/home/fedex/Isos" = {
    device = "/dev/vg-data/isos";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  fileSystems."/home/fedex/.local/share/Steam" = {
    device = "/dev/vg-main/gaming";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  fileSystems."/home/fedex/VMs" = {
    device = "/dev/vg-data/virtual-box-vms";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  fileSystems."/var/lib/ollama" = {
    device = "/dev/vg-data/ai-models";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
